version: '3.8'

services:
  # Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Pull the model on startup
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull llama3.2:1b && 
             wait"

  # RAG Engine Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./examples/configs/demo_local_config.json:/app/config.json:ro
      - ./demo_document.md:/app/demo_document.md:ro
    environment:
      - PYTHONPATH=/app
      - CONFIG_PATH=/app/config.json
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    command: python -m rag_engine serve --host 0.0.0.0 --port 8000

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
