version: '3.8'

services:
  rag-engine-fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RAG_CONFIG_PATH=/app/config/production.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./vector_store:/app/vector_store
    command: ["python", "-m", "rag_engine", "serve", "--config", "/app/config/production.json", "--framework", "fastapi", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  rag-engine-flask:
    build: .
    ports:
      - "8001:8001"
    environment:
      - RAG_CONFIG_PATH=/app/config/production.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./vector_store:/app/vector_store
    command: ["python", "-m", "rag_engine", "serve", "--config", "/app/config/production.json", "--framework", "flask", "--host", "0.0.0.0", "--port", "8001", "--workers", "3"]

  rag-engine-ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - RAG_CONFIG_PATH=/app/config/production.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./vector_store:/app/vector_store
    command: ["python", "-m", "rag_engine", "serve", "--config", "/app/config/production.json", "--ui", "streamlit", "--ui-port", "8501"]
    depends_on:
      - rag-engine-fastapi

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - rag-engine-fastapi
      - rag-engine-flask
      - rag-engine-ui
